name: codigitapi-ci
on:
  push:
    branches:
    - master
    paths:
    - 'Dockerfile'
    - '.github/workflows/**'
    - 'src/**'

  pull_request:
    branches:
    - master

jobs:
  test:
    name: testing rest api
    runs-on: ubuntu-latest
    steps:
    - run: echo 'testing REST API'
  build:
    name: building docker image and push
    environment: stage
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: login into docker hub
      run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

    - name: build docker image
      run: docker build -t courageabam/codigitapi:1.0 .

    - name: push image into docker hub
      run: docker push courageabam/codigitapi:1.0   

